### ISSUE TITLE
Unlisted Requirement fails on CentOS 7.4 w MariaDB

### ISSUE THREAD

**Issue by datakid** [Bioconductor/VariantAnnotation#1]
I'm trying to install VariantAnnotation in R 3.4.2 on CentOS 7.4

One of the errors is 

```
2: In install.packages(pkgs = doing, lib = lib, ...) :
  installation of package ‘RMySQL’ had non-zero exit status
```
I attempted to [install RMySQL yesterday and *that* failed too](https://github.com/r-dbi/RMySQL/issues/214) - although there is a fork work around, which is less than ideal.

Two things of note:
 - RMySQL isn't listed as a dependency on a new install of VariantAnnotation?
 - The [RMySQL page notes](https://github.com/r-dbi/RMySQL#rmysql) that it is being phased out for RMariaDB

**Comment by mtmorgan** [comment]
RMySQL is a dependency of a dependency; it's not usual in R to list recursive dependencies (of which there are 65 for VariantAnnotation, `pkgs = package_dependencies("VariantAnnotation", available.packages(repos=BiocInstaller::biocinstallRepos()), recursive=TRUE)`.

This belongs on the GenomicFeatures repository, where I'll try to reference this.
