### ISSUE TITLE
scanBcfHeader _hts_rewind() error in 1.29.19

### ISSUE THREAD

**Issue by smgogarten** [Bioconductor/VariantAnnotation#22]
One of my unit tests in SeqArray is now failing to read an example file:
```
vcffile <- SeqArray::seqExampleFileName("vcf")
vcf <- readVcf(vcffile, genome="hg19")
Error in scanBcfHeader(bf) : [internal] _hts_rewind() failed
```

**Comment by zhengxwen** [comment]
The VCF file in [SeqArray](
https://github.com/zhengxwen/SeqArray/commit/bd49ebfddc0e4457b1c2fb12cb3c62809ff21ae2) has been recompressed by bgzip, and it works with the latest VariantAnnotation.
