### ISSUE TITLE
How to output all records in INFO fild ?

### ISSUE THREAD

**Issue by qindan2008** [Bioconductor/VariantAnnotation#23]
Hello,
I have 64539 records in a vcf file.  The annotation information is in [INFO] fild, and [INFO] isn't the same in each record. 
For example,
![wechatimg4](https://user-images.githubusercontent.com/15100260/54025689-418bd280-41d6-11e9-8243-a3730230133a.jpeg)
Not all the records have the "ExAC_Het_AMR" annotation. How to output @info@listData$ExAC_Het_AMR@unlistData the same length as number of vcd records? And the missing data represented  by "NA" or "." ?

Thank you very much !

**Comment by lawremi** [comment]
You could call `drop(info(vcf)$ExAC_Het_AMR)`. Btw, please avoid accessing the internal slots of the object. It's more trouble than it's worth. Also, you might want tot ask future questions like this on support.bioconductor.org.

**Comment by qindan2008** [comment]
OK, Thanks.

**Comment by vobencha** [comment]
Looks like this one is resolved. Closing the issue.
