### ISSUE TITLE
indexVcf Fails if VCF File Not Compressed

### ISSUE THREAD

**Issue by DarioS** [Bioconductor/VariantAnnotation#33]
I looked at the documentation of `indexVcf` and it says nothing about requiring compressed files. However, 

```r
indexVcf("primaryTissue.merged.annotated.vcf")
Error in value[[3L]](cond) : file does not appear to be bgzip'd
```

**Comment by mtmorgan** [comment]
this is a limitation of the documentation; the constraint comes from underlying htslib / bcftools. Compressed files can be created with `Rsamtools::bgzip()`.
