### ISSUE TITLE
writeVcf save vcf with invalid contig information

### ISSUE THREAD

**Issue by thomasfaraut** [Bioconductor/VariantAnnotation#36]
If I read a valid vcf with the last 3.10 Bioconductor version 1.32.0

* when the vcf file contains a single contig, the ouput contig information is truncated and not valid 

```R
vcf <- readVcf("input_singlecontig.vcf")
writeVcf(vcf, "output_singlecontig.vcf")
```
head of input_singlecontig.vcf
```
##fileformat=VCFv4.2
##contig=<ID=10,length=135534747>
##ALT=<ID=INV,Description="Inversion">
```
head of output_singlecontig.vcf
```
##fileformat=VCFv4.2
##fileDate=20200109
##FILTER=<ID=PASS,Description="All filters passed">
##FILTER=<ID=LOW_QUAL,Description="Low quality call as specified by 'variantcalling.lowQuality'">
##contig=135534747
```

 * but works correctly when at least two contigs are present, e.g.
```
##contig=<ID=10,length=135534747>
##contig=<ID=11,length=135006516>
```
I am attaching the two files so that the error can be reproduced easily (extensions changed to .txt):
[input_singlecontig.txt](https://github.com/Bioconductor/VariantAnnotation/files/4040562/input_singlecontig.txt)
[output_singlecontig.txt](https://github.com/Bioconductor/VariantAnnotation/files/4040563/output_singlecontig.txt)

Thanks for you help!

**Comment by lshep** [comment]
Hello.  Thank you for the report. I'm following up on this now.  Can you provide the input file with two contigs so I can compare the output from valid to invalid?

**Comment by lshep** [comment]
Is this still an issue?

**Comment by lshep** [comment]
With no follow up information we are closing this issue.  If this i still an issue please request it be reopened with the requested additional information

**Comment by thomasfaraut** [comment]
Sorry for my late reaction.
I missed the first two emails because I dit not recognize it was related to the submitted issue.

The input file with two contigs could have simply be constructed by adding the line
```
 ##contig=<ID=11,length=135006516>
```
to the provided input_singlecontig.txt.

I didn't answered earlier to your two last emails because I encountered troubles to upgrade my Bioconductor installation (I tried even to reinstall) to be able to see if it was still an issue.
I am not using anymaore Bioconductor on a regular basis, this explains why it was difficult to me to reproduce the error.

I apologize again.

**Comment by lshep** [comment]
No worries.  Thank you for the additional information and letting us know it is still an issue.

**Comment by Lenbok** [comment]
Seems to me that this issue and #42 probably have exactly the same cause.
