### ISSUE TITLE
installation fail with error undefined symbol: hts_get_bgzfp

### ISSUE THREAD

**Issue by rladiesPHL** [Bioconductor/VariantAnnotation#37]
Hi 
I tried to install VariantAnnotation by BiocManager from bioconductor at R 3.6.0 (I have to use R 3.6 to compatible for another VariantAnnotation dependent package). I kept getting error 

```
Error: package or namespace load failed for ‘VariantAnnotation’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/home/suc1/R/x86_64-pc-linux-gnu-library/3.6/00LOCK-VariantAnnotation/00new/VariantAnnotation/libs/VariantAnnotation.so':
  /home/suc1/R/x86_64-pc-linux-gnu-library/3.6/00LOCK-VariantAnnotation/00new/VariantAnnotation/libs/VariantAnnotation.so: undefined symbol: hts_get_bgzfp
```
Anyone had similar problem and solved it before? 

hts_get_bgzfp should be a part of htslib. it is loaded in my system. Still not working.

**Comment by hpages** [comment]
We need a full transcript of what you did i.e. please show the command that you used for installing VariantAnnotation and the full output.

We also need to see the output of your `sessionInfo()`.

Thanks!

**Comment by lshep** [comment]
With no follow up information we are closing this issue.  If this continues to be an issue request the issue be reopened with the additional information requested.
