### ISSUE TITLE
extractROWS() on a CollapsedVCF instance returns an invalid object.

### ISSUE THREAD

**Issue by mtmorgan** [Bioconductor/VariantAnnotation#39]
@hpages VariantAnnotation fails in devel https://master.bioconductor.org/checkResults/3.11/bioc-LATEST/VariantAnnotation/malbec2-buildsrc.html because `extractROWS()` returns an invalid CollapsedVCF object. A simple example is
```r
fl <- system.file("extdata", "ex2.vcf",  package="VariantAnnotation")
vcf <- readVcf(fl, genome="hg19")
validObject(extractROWS(vcf, 1:2))
```
leading to
```
Error in validObject(extractROWS(vcf, 1:2)) :
  invalid class "CollapsedVCF" object: 1: 'fixed(object)' and 'rowRanges(object) must have the same number of rows
invalid class "CollapsedVCF" object: 2: 'info' must have the same number of rows as 'rowRanges'
```
It seems like the solution is to add
```diff
diff --git a/R/methods-VCF-class.R b/R/methods-VCF-class.R
index b1305c2..ae8e4ce 100644
--- a/R/methods-VCF-class.R
+++ b/R/methods-VCF-class.R
@@ -296,6 +296,10 @@ setMethod("vcfFields", "VCF",
 ### Subsetting and combining
 ###
 
+setMethod(vertical_slot_names, "VCF", function(x) {
+    c("fixed", "info", callNextMethod())
+})
+
 setMethod("[", c("VCF", "ANY", "ANY"),
     function(x, i, j, ..., drop=TRUE)
 {
```
Does that mean the `[` and `[<-` methods immediately following this can be removed?

**Comment by LiNk-NY** [comment]
FWIW, the package `TVTB` is experiencing issues related to this for `ExpandedVCF` based on what Kevin Rue-Albrecht has responded with:
> there is no `extractROWS` method defined for VCF objects. 
```r
> showMethods("extractROWS", classes = "ExpandedVCF")
Function: extractROWS (package S4Vectors)
x="ExpandedVCF", i="logical"
    (inherited from: x="Vector", i="ANY")
x="ExpandedVCF", i="numeric"
    (inherited from: x="Vector", i="ANY")
```
@hpages

**Comment by mtmorgan** [comment]
```
> selectMethod(extractROWS, "ExpendedVCF")
Method Definition:

function (x, i)
{
    if (is.null(x) || missing(i))
        return(x)
    ndim <- max(length(dim(x)), 1L)
    i <- normalizeSingleBracketSubscript(i, x, allow.NAs = TRUE,
        allow.append = TRUE)
    args <- rep.int(list(quote(expr = )), ndim)
    args[[1]] <- i
    args <- c(list(x), args, list(drop = FALSE))
    do.call(`[`, args)
}
<bytecode: 0x7fad35d4e590>
<environment: namespace:S4Vectors>

Signatures:
        x             i
target  "ExpendedVCF" "ANY"
defined "ANY"         "ANY"
```

**Comment by hpages** [comment]
Seems related to my [recent changes to SummarizedExperiment](https://github.com/Bioconductor/SummarizedExperiment/commit/81d41a110c1115df6ad5b144c40e6d171ab13c2f), sorry guys. I made these changes in preparation for a clean solution to the `c()` issue. See https://github.com/Bioconductor/SummarizedExperiment/issues/27 and https://github.com/Bioconductor/GenomicFiles/issues/4  

@mtmorgan Thanks for taking care of this! I'm not familiar with VCF objects but yes, it seems that the `fixed` and `info` slots should be registered as _vertical slots_. Don't remove the `[` and `[<-` methods for now. We shouldn't need them in theory, but they are doing strange things and I think we still need them for now. For the same reason I didn't remove the `[` and `[<-` methods for SummarizedExperiment objects yet. Modernizing the subsetting code for SummarizedExperiment objects will be a slow process that will require several iterations.

**Comment by kevinrue** [comment]
@kevinrue tagging myself to follow the conversation for `TVTB`

**Comment by mtmorgan** [comment]
@hpages https://github.com/Bioconductor/SummarizedExperiment/blob/81d41a110c1115df6ad5b144c40e6d171ab13c2f/R/SummarizedExperiment-class.R#L84 changes
```
x = SimpleList(setNames(nm = list()))  # named simple list
assays(SummarizedExperiment(assays = x))      # NULL
```
Previously this was an endomorphism. Is this intentional?
