### ISSUE TITLE
Conversion to VRanges Error

### ISSUE THREAD

**Issue by DarioS** [Bioconductor/VariantAnnotation#44]
I think that this worked in the past. I recently began working with Bioconductor 3.12.

```r
fl <- system.file("extdata", "ex2.vcf", package = "VariantAnnotation")
vcf <- readVcf(fl, genome = "hg19")
as(vcf, "VRanges") # Error in ans[] <- x : replacement has length zero
```

**Comment by mtmorgan** [comment]
I don't see this; is your installation valid? `BiocManager::valid()` should return TRUE, and `BiocManager::version()` should return 3.12.

**Comment by DarioS** [comment]
Indeed, it seems like the recent upgrade failed for a small number of packages. I should have checked first.
