### ISSUE TITLE
SNPlocs version in vignette needs updating

### ISSUE THREAD

**Issue by jwokaty** [Bioconductor/VariantAnnotation#63]
From @vjcitn via https://devteam-bioc.slack.com/archives/C4VR9ABBP/p1660139066145949
> ```
> Error: processing vignette 'VariantAnnotation.Rnw' failed with diagnostics:
>  chunk 16 (label = examine_dbSNP) 
> Error in library(SNPlocs.Hsapiens.dbSNP.20101109) : 
>   there is no package called 'SNPlocs.Hsapiens.dbSNP.20101109'
> ```
> that happens in 3.16 on lconway.  The reason is that that SNPlocs version is I guess retired, but the other platforms have an old version on hand?  The vignette can likely be updated to involve a non-defunct SNPlocs.

**Comment by hpages** [comment]
Taken care of in **VariantAnnotation** 1.43.3 (see commit 505509cfd5a2e42514504fb95972fb96aa19ff21).
